import Image from "next/image";
import { Card } from "@/components/ui/Card";
import { Reveal } from "@/components/ui/Reveal";
import { Button } from "@/components/ui/Button";
import { SectionHeading } from "@/components/ui/SectionHeading";
import { SmartForm } from "@/components/ui/FormFields";
import { contactDetails, detailedServices, faq, projects, roles, solutions, team } from "@/data/site";
import { meetingUrl } from "@/lib/utils";

export function PageHero({ title, text, actions }: { title: string; text: string; actions?: React.ReactNode }) {
  return <section className="dark-mesh px-4 pb-20 pt-36 text-white md:px-6 md:pt-44"><Reveal className="mx-auto max-w-5xl text-center"><h1 className="font-display text-5xl font-bold tracking-tight md:text-7xl">{title}</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-white/72">{text}</p>{actions ? <div className="mt-8 flex flex-wrap justify-center gap-3">{actions}</div> : null}</Reveal></section>;
}

export function AboutPage() {
  return <><PageHero title="We Build Intelligent Systems for Real-World Progress." text="Omixa Labs combines artificial intelligence, automation, machine learning, design, and software engineering to help organizations solve complex problems and operate more effectively." /><main className="mesh-bg px-4 py-20 md:px-6"><div className="mx-auto max-w-7xl"><Reveal className="max-w-4xl"><SectionHeading title="Our work begins with understanding the problem. Technology comes next." /><p className="text-lg leading-8 text-muted">Omixa Labs was created around a simple idea: powerful technology should make work easier, decisions clearer, and businesses stronger.</p><p className="mt-5 text-lg leading-8 text-muted">We work with organizations to identify where intelligence and automation can create meaningful impact. From AI agents and machine learning models to custom platforms and connected workflows, we build solutions that are practical, scalable, and designed for real use.</p></Reveal><div className="mt-12 grid gap-5 md:grid-cols-2"><Card><h2 className="font-display text-2xl font-bold">Mission</h2><p className="mt-3 text-muted">To make intelligent technology practical, accessible, and valuable for businesses of every size.</p></Card><Card><h2 className="font-display text-2xl font-bold">Vision</h2><p className="mt-3 text-muted">To become a trusted global partner for organizations building the next generation of intelligent products, services, and operations.</p></Card></div><SectionHeading eyebrow="Values" title="Principles that shape the work" /><div className="grid gap-4 md:grid-cols-3">{["Practical Innovation", "Excellence", "Integrity", "Human-Centred Design", "Collaboration", "Continuous Improvement"].map((v) => <Card key={v}><h3 className="font-bold">{v}</h3></Card>)}</div><SectionHeading eyebrow="Team" title="Editable team profiles" /><div className="grid gap-5 md:grid-cols-3">{team.map((m) => <Card key={m.name}><Image src={m.image} alt={`${m.name}, ${m.role}`} width={640} height={640} className="mb-5 aspect-square w-full rounded-md object-cover" /><h3 className="font-display text-xl font-bold">{m.name}</h3><p className="text-sm font-bold text-electric">{m.role}</p><p className="mt-3 text-sm leading-7 text-muted">{m.bio}</p><a href="#" className="mt-4 inline-block text-sm font-bold text-electric">LinkedIn</a></Card>)}</div></div></main></>;
}

export function ServicesPage() {
  return <><PageHero title="AI, Automation, and Software Services" text="Detailed services for companies that need practical intelligent systems, connected workflows, and reliable delivery." /><main className="mesh-bg px-4 py-20 md:px-6"><div className="mx-auto grid max-w-7xl gap-6">{detailedServices.map((s) => <Card key={s.title}><div className="grid gap-8 lg:grid-cols-[1fr_1.4fr]"><div><h2 className="font-display text-3xl font-bold">{s.title}</h2><p className="mt-4 text-muted">{s.description}</p><div className="mt-6"><Button href="/contact">Discuss this service</Button></div></div><div className="grid gap-4 md:grid-cols-3"><List title="Benefits" items={s.benefits} /><List title="Use cases" items={s.useCases} /><List title="Delivery" items={s.process} /></div></div></Card>)}</div></main></>;
}

export function SolutionsPage() {
  return <><PageHero title="Solutions Organized Around Business Needs" text="Use AI where it can remove friction, improve decisions, and strengthen the way teams operate." /><main className="mesh-bg px-4 py-20 md:px-6"><div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-2">{solutions.map((s) => <Card key={s.title}><s.icon className="text-electric" /><h2 className="mt-5 font-display text-2xl font-bold">{s.title}</h2><p className="mt-3 leading-7 text-muted">{s.text}</p><div className="mt-5"><Button href="/contact" variant="ghost">Plan a solution</Button></div></Card>)}</div></main></>;
}

export function CareersPage() {
  const fields = [{ name: "name", label: "Full name", required: true }, { name: "email", label: "Email address", type: "email", required: true }, { name: "phone", label: "Phone number", required: true }, { name: "country", label: "Country", required: true }, { name: "position", label: "Position applying for", required: true, options: roles.map((r) => r.title) }, { name: "experience", label: "Years of experience", type: "number", required: true }, { name: "availability", label: "Availability", required: true }, { name: "cover", label: "Short introduction", type: "textarea", required: true }];
  return <><PageHero title="Join Our Operations Team." text="Apply for general roles in customer care, data entry, administration, sales support, and daily business operations." actions={<><Button href={meetingUrl}>Join Interview</Button><Button href="#apply" variant="secondary">Apply Now</Button></>} /><main className="mesh-bg px-4 py-20 md:px-6"><div className="mx-auto max-w-7xl"><SectionHeading title="Open roles" /><div className="grid gap-5 md:grid-cols-3">{roles.map((r) => <Card key={r.title}><h2 className="font-display text-xl font-bold">{r.title}</h2><p className="mt-2 text-sm text-electric">{r.department} - {r.location}</p><p className="mt-3 text-sm text-muted">{r.type} - {r.level}</p><p className="mt-3 text-sm leading-7 text-muted">{r.description}</p><Button href="#apply" variant="ghost" className="mt-5">View role</Button></Card>)}</div><div id="apply" className="mt-16 grid gap-8 lg:grid-cols-2"><div><h2 className="font-display text-4xl font-bold">Application form</h2><p className="mt-4 text-muted">PDF CV uploads are validated in the browser with a 10 MB maximum file size.</p><div className="mt-8 grid gap-3">{["Application", "Initial Review", "Online Interview", "General Assessment", "Final Conversation", "Offer and Onboarding"].map((x, i) => <p key={x} className="rounded-md bg-white p-4 text-sm font-semibold shadow-sm">{i + 1}. {x}</p>)}</div><p className="mt-4 text-sm text-muted">Candidates may answer preliminary questions before the formal onboarding stage.</p></div><SmartForm fields={fields} fileUpload submitLabel="Submit application" formName="Careers application form" /></div></div></main></>;
}

export function ProjectsPage() {
  return <><PageHero title="Sample Project Portfolio" text="Fictional examples showing how Omixa Labs solutions can be structured across AI agents, automation, machine learning, platforms, data systems, and consulting." /><main className="mesh-bg px-4 py-20 md:px-6"><div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-2">{projects.map((p) => <Card key={p.title}><Image src={p.image} alt={p.title} width={960} height={540} className="mb-5 aspect-[16/9] w-full rounded-md object-cover" /><p className="text-xs font-bold uppercase tracking-[0.16em] text-electric">Sample project - {p.category}</p><h2 className="mt-3 font-display text-2xl font-bold">{p.title}</h2><p className="mt-3 text-muted">{p.description}</p><div className="mt-5 grid gap-3 text-sm text-muted"><p><b>Client industry:</b> {p.industry}</p><p><b>Problem:</b> {p.problem}</p><p><b>Solution:</b> {p.solution}</p><p><b>Technologies:</b> {p.technologies.join(", ")}</p><p><b>Results:</b> {p.results}</p></div><Button href="/contact" variant="ghost" className="mt-5">Request case study</Button></Card>)}</div></main></>;
}

export function ContactPage() {
  const fields = [{ name: "name", label: "Full name", required: true }, { name: "email", label: "Work email", type: "email", required: true }, { name: "phone", label: "Phone number", required: true }, { name: "company", label: "Company name", required: true }, { name: "job", label: "Job title", required: true }, { name: "service", label: "Service required", required: true, options: ["AI Agents", "Automation", "Machine Learning", "Chatbots", "Custom Software", "Consulting"] }, { name: "budget", label: "Estimated budget", required: true, options: ["Under $10k", "$10k - $25k", "$25k - $75k", "$75k+"] }, { name: "timeline", label: "Project timeline", required: true }, { name: "details", label: "Project details", type: "textarea", required: true }];
  return <><PageHero title="Let's Build Something Intelligent Together." text="Share your project, operational challenge, or business idea. Our team will help you identify the right approach." /><main className="mesh-bg px-4 py-20 md:px-6"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[1.2fr_0.8fr]"><SmartForm fields={fields} submitLabel="Submit project inquiry" formName="Contact project inquiry form" /><div className="grid gap-5"><Card><h2 className="font-display text-2xl font-bold">Contact details</h2>{Object.entries(contactDetails).filter(([k]) => k !== "socials").map(([k, v]) => <p key={k} className="mt-3 text-muted"><b className="capitalize text-ink">{k}:</b> {v}</p>)}</Card><Card><h2 className="font-display text-2xl font-bold">FAQ</h2>{faq.map((q) => <details key={q} className="border-b border-ink/10 py-3"><summary className="cursor-pointer font-semibold">{q}</summary><p className="mt-2 text-sm text-muted">Omixa Labs scopes every engagement around practical requirements, security needs, timeline, and expected business value.</p></details>)}</Card></div></div></main></>;
}

function List({ title, items }: { title: string; items: string[] }) {
  return <div><h3 className="font-bold">{title}</h3><ul className="mt-3 grid gap-2 text-sm text-muted">{items.map((i) => <li key={i}>- {i}</li>)}</ul></div>;
}
